<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <GenerateProgramFile>false</GenerateProgramFile>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/DotNetAxi.DotNet/DotNetAxi.DotNet.csproj" />
    <ProjectReference Include="../../src/DotNetAxi.Workspaces/DotNetAxi.Workspaces.csproj" />
    <ProjectReference Include="../DotNetAxi.Testing/DotNetAxi.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None
      Include="../Fixtures/**/*"
      Link="Fixtures/%(RecursiveDir)%(Filename)%(Extension)"
      CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
