<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <PackageVersion>9.8.7-test</PackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata
      Include="DotNetAxi.ToolVersion"
      Value="$(PackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/DotNetAxi.Cli/DotNetAxi.Cli.csproj" />
    <ProjectReference Include="../../src/DotNetAxi.Contracts/DotNetAxi.Contracts.csproj" />
    <ProjectReference Include="../../src/DotNetAxi.Structural/DotNetAxi.Structural.csproj" />
    <ProjectReference Include="../../src/DotNetAxi.Workspaces/DotNetAxi.Workspaces.csproj" />
  </ItemGroup>
</Project>
