<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DotNetAxi.Testing.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/DotNetAxi.Contracts/DotNetAxi.Contracts.csproj" />
    <ProjectReference Include="../../src/DotNetAxi.DotNet/DotNetAxi.DotNet.csproj" />
  </ItemGroup>
</Project>
