using System.Text.RegularExpressions;

namespace DotNetAxi.Cli.Tests;

public sealed class SymbolWorkspaceScopeTests
{
    [Fact]
    public async Task Test_and_generated_identity_trajectory_preserves_one_scope()
    {
        using var workspace = new TestWorkspace();
        await workspace.WriteAsync(
            "src/App/App.csproj",
            "<Project Sdk=\"Microsoft.NET.Sdk\" />");
        await workspace.WriteAsync("src/App/Product.cs", "public class Product { }");
        await workspace.WriteAsync(
            "tests/App.Tests/App.Tests.csproj",
            "<Project Sdk=\"Microsoft.NET.Sdk\" />");
        await workspace.WriteAsync(
            "tests/App.Tests/TestOnly.cs",
            "public class TestOnly { public void Verify() { } }");
        await workspace.WriteAsync(
            "tests/App.Tests/Generated.g.cs",
            "// <auto-generated/>\npublic class GeneratedOnly { }");
        await workspace.WriteAsync(
            "Demo.slnx",
            "<Solution><Project Path=\"src/App/App.csproj\" /><Project Path=\"tests/App.Tests/App.Tests.csproj\" /></Solution>");

        var excluded = await workspace.RunAsync(
            "search", "symbol", "TestOnly",
            "--solution", "Demo.slnx",
            "--full");
        var search = await workspace.RunAsync(
            "search", "symbol", "TestOnly",
            "--solution", "Demo.slnx",
            "--include-tests",
            "--fields", "id,owning_projects",
            "--full");
        var id = SymbolId(search.Output);
        var defaultShow = await workspace.RunAsync(
            "show", "symbol", id,
            "--solution", "Demo.slnx");
        var show = await workspace.RunAsync(
            "show", "symbol", id,
            "--solution", "Demo.slnx",
            "--include-tests",
            "--max-chars", "1");
        var outline = await workspace.RunAsync(
            "outline", id,
            "--solution", "Demo.slnx",
            "--include-tests",
            "--limit", "1");

        Assert.Equal(0, excluded.ExitCode);
        Assert.Contains("count: 0", excluded.Output);
        Assert.Equal(0, search.ExitCode);
        Assert.NotEqual(Snapshot(excluded.Output), Snapshot(search.Output));
        Assert.Equal(1, defaultShow.ExitCode);
        Assert.Contains("code: evidence.stale_id", defaultShow.Output);
        Assert.Equal(0, show.ExitCode);
        Assert.Equal(0, outline.ExitCode);
        Assert.Equal(Snapshot(search.Output), Snapshot(show.Output));
        Assert.Equal(Snapshot(search.Output), Snapshot(outline.Output));
        Assert.Contains("include_tests: true", show.Output);
        Assert.Contains("include_generated: false", show.Output);
        Assert.Contains(
            "--solution 'Demo.slnx' --include-tests --max-chars",
            show.Output);

        var generatedSearch = await workspace.RunAsync(
            "search", "symbol", "GeneratedOnly",
            "--solution", "Demo.slnx",
            "--include-tests",
            "--include-generated",
            "--fields", "id",
            "--full");
        var generatedId = SymbolId(generatedSearch.Output);
        var generatedExcluded = await workspace.RunAsync(
            "show", "symbol", generatedId,
            "--solution", "Demo.slnx",
            "--include-tests");
        var generatedShow = await workspace.RunAsync(
            "show", "symbol", generatedId,
            "--solution", "Demo.slnx",
            "--include-tests",
            "--include-generated");

        Assert.Equal(0, generatedSearch.ExitCode);
        Assert.Equal(1, generatedExcluded.ExitCode);
        Assert.Equal(0, generatedShow.ExitCode);
        Assert.Equal(Snapshot(generatedSearch.Output), Snapshot(generatedShow.Output));
    }

    [Fact]
    public async Task Multiple_root_solutions_require_an_explicit_selector()
    {
        using var workspace = new TestWorkspace();
        await workspace.WriteAsync("one/One.csproj", "<Project Sdk=\"Microsoft.NET.Sdk\" />");
        await workspace.WriteAsync("one/One.cs", "public class OneOnly { }");
        await workspace.WriteAsync("two/Two.csproj", "<Project Sdk=\"Microsoft.NET.Sdk\" />");
        await workspace.WriteAsync("two/Two.cs", "public class TwoOnly { }");
        await workspace.WriteAsync(
            "One.slnx",
            "<Solution><Project Path=\"one/One.csproj\" /></Solution>");
        await workspace.WriteAsync(
            "Two.slnx",
            "<Solution><Project Path=\"two/Two.csproj\" /></Solution>");

        var ambiguous = await workspace.RunAsync(
            "search", "symbol", "Only", "--full");
        var selected = await workspace.RunAsync(
            "search", "symbol", "Only",
            "--solution", "One.slnx",
            "--full");
        var conflict = await workspace.RunAsync(
            "search", "symbol", "Only",
            "--solution", "One.slnx",
            "--project", "one/One.csproj",
            "--full");

        Assert.Equal(2, ambiguous.ExitCode);
        Assert.Contains("code: usage.workspace_selector_ambiguous", ambiguous.Output);
        Assert.Contains("candidate_paths[2]: One.slnx,Two.slnx", ambiguous.Output);
        Assert.Contains("--solution", ambiguous.Output);
        Assert.Equal(0, selected.ExitCode);
        Assert.Contains("solution: One.slnx", selected.Output);
        Assert.Contains("OneOnly", selected.Output);
        Assert.DoesNotContain("TwoOnly", selected.Output);
        Assert.Equal(2, conflict.ExitCode);
        Assert.Contains("code: usage.workspace_selector_conflict", conflict.Output);
    }

    [Fact]
    public async Task Linked_files_are_deduplicated_without_losing_owners_or_variants()
    {
        using var workspace = new TestWorkspace();
        await workspace.WriteAsync("Shared.cs", "public class SharedDeclaration { }");
        await workspace.WriteAsync(
            "app/App.csproj",
            "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><TargetFrameworks>net8.0;net10.0</TargetFrameworks></PropertyGroup><ItemGroup><Compile Include=\"../Shared.cs\" /></ItemGroup></Project>");
        await workspace.WriteAsync(
            "tests/App.Tests.csproj",
            "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup><ItemGroup><Compile Include=\"../Shared.cs\" /></ItemGroup></Project>");
        await workspace.WriteAsync(
            "Combined.slnx",
            "<Solution><Project Path=\"app/App.csproj\" /><Project Path=\"app/App.csproj\" /><Project Path=\"tests/App.Tests.csproj\" /></Solution>");

        var project = await workspace.RunAsync(
            "search", "symbol", "SharedDeclaration",
            "--project", "app/App.csproj",
            "--path", "Shared.cs",
            "--fields", "owning_project_count,owning_projects,variant_count,variants",
            "--full");
        var solution = await workspace.RunAsync(
            "search", "symbol", "SharedDeclaration",
            "--solution", "Combined.slnx",
            "--include-tests",
            "--fields", "owning_project_count,owning_projects,variant_count,variants",
            "--full");

        Assert.Equal(0, project.ExitCode);
        Assert.Contains("count: 1", project.Output);
        Assert.Contains("paths[1]: Shared.cs", project.Output);
        Assert.Contains("owning_project_count: 1", project.Output);
        Assert.Contains("variant_count: 2", project.Output);
        Assert.Equal(0, solution.ExitCode);
        Assert.Contains("count: 1", solution.Output);
        Assert.Contains("projects[2]: app/App.csproj,tests/App.Tests.csproj", solution.Output);
        Assert.Contains("owning_project_count: 2", solution.Output);
        Assert.Contains("variant_count: 3", solution.Output);
        Assert.Contains("net8.0", solution.Output);
        Assert.Contains("net10.0", solution.Output);
    }

    [Fact]
    public async Task Missing_solution_member_remains_a_passive_scope_owner()
    {
        using var workspace = new TestWorkspace();
        await workspace.WriteAsync(
            "Missing.slnx",
            "<Solution><Project Path=\"missing/Missing.csproj\" /></Solution>");
        await workspace.WriteAsync(
            "missing/Source.cs",
            "public class MissingMemberDeclaration { }");

        var result = await workspace.RunAsync(
            "search", "symbol", "MissingMemberDeclaration",
            "--solution", "Missing.slnx",
            "--fields", "owning_project_count,owning_projects,variants",
            "--full");

        Assert.Equal(0, result.ExitCode);
        Assert.Contains("solution: Missing.slnx", result.Output);
        Assert.Contains("projects[1]: missing/Missing.csproj", result.Output);
        Assert.Contains("count: 1", result.Output);
        Assert.Contains("owning_project_count: 1", result.Output);
        Assert.Contains(
            "owning_projects[1]: missing/Missing.csproj",
            result.Output);
        Assert.Contains("unresolved", result.Output);
    }

    private static string SymbolId(string output) =>
        Regex.Match(
            output,
            @"symbol/v2/[A-Za-z0-9_-]+/[a-f0-9]{64}/[a-f0-9]{64}").Value;

    private static string Snapshot(string output) =>
        Regex.Match(output, @"^snapshot: (ws_[a-f0-9]{64})$", RegexOptions.Multiline)
            .Groups[1]
            .Value;

    private sealed class TestWorkspace : IDisposable
    {
        public TestWorkspace()
        {
            Root = Path.Combine(
                Path.GetTempPath(),
                "dotnet-axi-symbol-workspace-scope-tests",
                Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(Root);
        }

        public string Root { get; }

        public async Task WriteAsync(string relativePath, string contents)
        {
            var path = Path.Combine(
                Root,
                relativePath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            await File.WriteAllTextAsync(path, contents);
        }

        public async Task<(int ExitCode, string Output)> RunAsync(
            params string[] arguments)
        {
            var start = new System.Diagnostics.ProcessStartInfo
            {
                FileName = Environment.GetEnvironmentVariable("DOTNET_HOST_PATH")
                    ?? "dotnet",
                WorkingDirectory = Root,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
            };
            start.ArgumentList.Add(typeof(Cli.Program).Assembly.Location);
            foreach (var argument in arguments)
            {
                start.ArgumentList.Add(argument);
            }

            using var process = System.Diagnostics.Process.Start(start)!;
            var output = await process.StandardOutput.ReadToEndAsync();
            var error = await process.StandardError.ReadToEndAsync();
            await process.WaitForExitAsync();
            Assert.True(
                string.IsNullOrEmpty(error),
                $"Expected empty stderr, got: {error}");
            return (process.ExitCode, output);
        }

        public void Dispose()
        {
            if (Directory.Exists(Root))
            {
                Directory.Delete(Root, recursive: true);
            }
        }
    }
}
