<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="DotNetAxi.Roslyn" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../DotNetAxi.Contracts/DotNetAxi.Contracts.csproj" />
  </ItemGroup>
</Project>
