namespace DotNetAxi.Workspaces;

public static class WorkspaceGeneratedCodeClassifier
{
    public const int MaximumHeaderCharacters = 4096;

    public static bool HasGeneratedHeader(string text)
    {
        ArgumentNullException.ThrowIfNull(text);
        var header = text.AsSpan(
            0,
            Math.Min(MaximumHeaderCharacters, text.Length));
        return header.Contains(
                "<auto-generated",
                StringComparison.OrdinalIgnoreCase)
            || header.Contains(
                "<autogenerated",
                StringComparison.OrdinalIgnoreCase);
    }
}
