namespace DotNetAxi.Workspaces;

public static class WorkspaceGeneratedCodeClassifier
{
    public static bool HasGeneratedHeader(string text)
    {
        ArgumentNullException.ThrowIfNull(text);
        const int maximumCharacters = 4096;
        var header = text.AsSpan(
            0,
            Math.Min(maximumCharacters, text.Length));
        return header.Contains(
                "<auto-generated",
                StringComparison.OrdinalIgnoreCase)
            || header.Contains(
                "<autogenerated",
                StringComparison.OrdinalIgnoreCase);
    }
}
