<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio"><PrivateAssets>all</PrivateAssets></PackageReference>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DotNetAxi.Roslyn/DotNetAxi.Roslyn.csproj" />
    <ProjectReference Include="../../src/DotNetAxi.Structural/DotNetAxi.Structural.csproj" />
    <ProjectReference Include="../../src/DotNetAxi.Workspaces/DotNetAxi.Workspaces.csproj" />
  </ItemGroup>
</Project>
